### ISSUE TITLE
Class attributes on column 60 do not match

### ISSUE THREAD

**Issue by oonuttlet** [R-ArcGIS/arcgisgeocode#15]
See conversation here: https://twitter.com/oonuttlet/status/1783954337451901282

A dataframe returned by `geocode_addresses()` which contains both POINT features and empty GEOMETRYCOLLECTIONS cannot be row-bound due to differing classes. see reprex below:

```
library(arcgisgeocode)

addr <- rep("NULL", 27000)
addr[1] = "400 WASHINGTON AVE"
city <- sample(c("MIDDLE RIVER", "ESSEX", "DUNDALK", "TOWSON", "CATONSVILLE", "NULL"), 27000, replace = T)
city[1] = "TOWSON"
baltco_geo <- geocode_server(r"(https://bcgisdata.baltimorecountymd.gov/arcgis/rest/services/Geocoders/CompositeGeocoder/GeocodeServer)")

tst_geo_onlynull <- geocode_addresses(address = addr[2:length(addr)],
                                      city = city[2:length(addr)],
                                      geocoder = baltco_geo,
                                      .progress = FALSE) #since all are empty geoms, this runs correctly

tst_geo_nonull <- geocode_addresses(address = addr[1],
                                    city = city[1],
                                    geocoder = baltco_geo,
                                    .progress = FALSE) #since all have matches, this runs correctly

tst_geo_all <- geocode_addresses(address = addr,
                  city = city,
                  geocoder = baltco_geo,
                  .progress = FALSE) #mixing points and empty geometries creates differing classes for col 60, so cannot bind
```

not as intimately familiar with {sf} classes as I should be, but could this be remedied by converting column 60 to an empty POINT feature explicitly using `sfc_as_sf()` before binding?

**Comment by JosiahParry** [comment]
Thank you for this! Is the baltimore geocoder accessible to the public? I tried this with the world geocoder and just 10 records which all succeeded. I'll give this some more time

**Comment by JosiahParry** [comment]
Okay, so this works: 

```r
library(arcgisgeocode)

addr <- rep("NULL", 100)
addr[1] = "400 WASHINGTON AVE"
city <- sample(c("MIDDLE RIVER", "ESSEX", "DUNDALK", "TOWSON", "CATONSVILLE", "NULL"), 100, replace = T)
city[1] = "TOWSON"

baltco_geo <- geocode_server(r"(https://bcgisdata.baltimorecountymd.gov/arcgis/rest/services/Geocoders/CompositeGeocoder/GeocodeServer)")

#mixing points and empty geometries creates differing classes for col 60, so cannot bind
tst_geo_all <- geocode_addresses(
  address = addr,
  city = city,
  geocoder = baltco_geo,
  .progress = FALSE
) 
```

Notably we get this: 
<img width="236" alt="image" src="https://github.com/R-ArcGIS/arcgisgeocode/assets/13534508/60538979-c230-4406-9041-e1225d9e1c28">

I think it may have been fixed by a commit literally a few hours ago lol 
https://github.com/R-ArcGIS/arcgisutils/commit/2a377324b4c509d6775bf35375ecd4b25c665fd0

**Comment by JosiahParry** [comment]
Ah! SO this is actually a bug in the `arcgisutils` package and not the geocoding package. 

so run `pak::pak("r-arcgis/arcgisutils")` to get the updated utils package

 The utils package has a function `rbind_results()` which is used here as well as in `arcgislayers` (or will be idk if its there yet lol) which takes a list of data.frames or NULL objects and squishes them together.

**Comment by JosiahParry** [comment]
Should update the minimum version required

**Comment by oonuttlet** [comment]
updating arcgisutils didn't seem to change anything; still getting the error on my end. still getting GEOMETRYCOLLECTION EMPTY for the "NULL" records and POINT for the non-null records. i'll try again monday, maybe dependencies will have updated!

**Comment by JosiahParry** [comment]
I'm unable to make a geometry collection. Do you know the incantation to make one? I'll also make sure that r-universe make a new binary this weekend!

**Comment by oonuttlet** [comment]
the function is `sf::st_geometrycollection()`, which creates a geometrycollection which can then be passed into `st_sfc()` and bound to the original dataframe again:

```r
tst_geo_nonull_gc <- st_geometrycollection(st_geometry(tst_geo_nonull)) |>
  st_sfc() |>
  as.data.frame()

tst_geo_nonull_out <- cbind(st_drop_geometry(tst_geo_nonull), tst_geo_nonull_gc)
```

however, this still errors:
```r
Error in collapse::rowbind(tst_geo_nonull_out, tst_geo_onlynull) : 
  Class attribute on column 60 of item 2 does not match with column 60 of item 1.
```

I also tried using `st_collection_extract(x, "POINT")`, which should extract all point features from a geometrycollection, but that failed with a weird `{sf}` error:
```r
Error: attr classes has wrong size: please file an issue
```

I haven't yet filed an error in `{sf}`, but my guess is that since the geometrycollection returned by `geocode_addresses()` doesn't have any geometrycollections containing `POINT EMPTY`, there's nothing for it to extract and so it errors. which i think brings me to the crux of the error: why is my function returning `GEOMETRYCOLLECTION EMPTY` instead of `POINT EMPTY`?

my session info:

```r
R version 4.4.0 (2024-04-24 ucrt)
Platform: x86_64-w64-mingw32/x64
Running under: Windows 10 x64 (build 19045)

Matrix products: default


locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

time zone: America/New_York
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] arcgisutils_0.2.0.9000   sf_1.0-16                arcgisgeocode_0.0.0.9004

loaded via a namespace (and not attached):
 [1] R6_2.5.1            collapse_2.0.13     e1071_1.7-14        magrittr_2.0.3      rappdirs_0.3.3     
 [6] glue_1.7.0          RcppSimdJson_0.1.11 KernSmooth_2.23-22  parallel_4.4.0      lifecycle_1.0.4    
[11] classInt_0.4-10     cli_3.6.2           pak_0.7.2           grid_4.4.0          DBI_1.2.2          
[16] data.table_1.15.4   proxy_0.4-27        class_7.3-22        compiler_4.4.0      rstudioapi_0.16.0  
[21] tools_4.4.0         curl_5.2.1          Rcpp_1.0.12         httr2_1.0.1         rlang_1.1.3        
[26] units_0.8-5 
```

i _just_ (like an hour ago) updated to R 4.4.0, so these are all fresh package installs... not sure if there's an option in `{sf}` that might differ between us? perhaps how it's parsing the res json?

**Comment by JosiahParry** [comment]
I genuinely do not know why you would be getting a `GEOMETRYCOLLECTION` and not an empty point. 

Can you please run the following reprex right now I am unable to reproduce this issue

```r
reprex::reprex({
# print arcgisutils function body:
arcgisutils::rbind_results

library(arcgisgeocode)

addr <- rep("NULL", 100)
addr[1] = "400 WASHINGTON AVE"
city <- sample(c("MIDDLE RIVER", "ESSEX", "DUNDALK", "TOWSON", "CATONSVILLE", "NULL"), 100, replace = T)
city[1] = "TOWSON"

baltco_geo <- geocode_server(r"(https://bcgisdata.baltimorecountymd.gov/arcgis/rest/services/Geocoders/CompositeGeocoder/GeocodeServer)")

#mixing points and empty geometries creates differing classes for col 60, so cannot bind
tst_geo_all <- geocode_addresses(
  address = addr,
  city = city,
  geocoder = baltco_geo,
  .progress = FALSE
) 
})
```

**Comment by oonuttlet** [comment]
``` r
# print arcgisutils function body:
arcgisutils::rbind_results
#> function (x, call = rlang::current_env(), .ptype = data.frame()) 
#> {
#>     for (item in x) {
#>         check_data_frame(item, allow_null = TRUE, call = call, 
#>             arg = rlang::caller_arg(x))
#>     }
#>     return_sf <- all(vapply(x, inherits_or_null, logical(1), 
#>         class = "sf"))
#>     missing_elements <- vapply(x, is.null, logical(1))
#>     are_missing <- which(missing_elements)
#>     if (all(missing_elements)) {
#>         return(structure(data.frame(), null_elements = are_missing))
#>     }
#>     if (rlang::is_installed("collapse", version = "2.0.0")) {
#>         x <- collapse::rowbind(x, return = 2L)
#>     }
#>     else if (rlang::is_installed("data.table")) {
#>         x <- data.table::rbindlist(x)
#>         data.table::setDF(x)
#>     }
#>     else if (rlang::is_installed("vctrs")) {
#>         x <- vctrs::list_unchop(x, error_call = call)
#>     }
#>     else {
#>         x <- do.call(rbind.data.frame, x)
#>     }
#>     if (return_sf && !rlang::inherits_any(x, "sf")) {
#>         x <- sf::st_as_sf(x)
#>     }
#>     if (length(are_missing) > 0) {
#>         attr(x, "null_elements") <- are_missing
#>     }
#>     x
#> }
#> <bytecode: 0x00000228616accc0>
#> <environment: namespace:arcgisutils>

library(arcgisgeocode)

addr <- rep("NULL", 100)
addr[1] = "400 WASHINGTON AVE"
city <- sample(c("MIDDLE RIVER", "ESSEX", "DUNDALK", "TOWSON", "CATONSVILLE", "NULL"), 100, replace = T)
city[1] = "TOWSON"

baltco_geo <- geocode_server(r"(https://bcgisdata.baltimorecountymd.gov/arcgis/rest/services/Geocoders/CompositeGeocoder/GeocodeServer)")

#mixing points and empty geometries creates differing classes for col 60, so cannot bind
tst_geo_all <- geocode_addresses(
  address = addr,
  city = city,
  geocoder = baltco_geo,
  .progress = FALSE
)
```

<sup>Created on 2024-04-27 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

that worked!! would it have something to do with the size of the vector? I legitimately can't think of anything else that would differ here...

**Comment by JosiahParry** [comment]
okay cool that worked! Now I've tried cranking up N = 10,000 and that caused your error. 
<img width="830" alt="image" src="https://github.com/R-ArcGIS/arcgisgeocode/assets/13534508/3874fb63-0504-4f43-aa36-30ba2bd49a5e">

**Comment by JosiahParry** [comment]
Thank you for humoring me!!

**Comment by JosiahParry** [comment]
Got it. `sf::st_sfc(replicate(10, NULL))`

This occurs only when every single feature in the batch has no geometry

**Comment by oonuttlet** [comment]
aha! i was about to write that the error occurs at `n = 1001`. is default batch size 1000?

**Comment by JosiahParry** [comment]
The default batch size is determined by the geocoding service here the `N = 1000` but for the Esri geocoder I think it is 150, for example. 

<img width="538" alt="image" src="https://github.com/R-ArcGIS/arcgisgeocode/assets/13534508/03f0d282-8140-4a07-a7b3-f10bb36dc0df">

**Comment by JosiahParry** [comment]
Alright, we got it! Pushing a change momentarily.

**Comment by oonuttlet** [comment]
checks out. i am intrigued, though: when I try and add a second valid address into the middle of the vectors, it still returns `GEOMETRYCOLLECTION EMPTY`. see reprex:

``` r
# print arcgisutils function body:
arcgisutils::rbind_results
#> function (x, call = rlang::current_env(), .ptype = data.frame()) 
#> {
#>     for (item in x) {
#>         check_data_frame(item, allow_null = TRUE, call = call, 
#>             arg = rlang::caller_arg(x))
#>     }
#>     return_sf <- all(vapply(x, inherits_or_null, logical(1), 
#>         class = "sf"))
#>     missing_elements <- vapply(x, is.null, logical(1))
#>     are_missing <- which(missing_elements)
#>     if (all(missing_elements)) {
#>         return(structure(data.frame(), null_elements = are_missing))
#>     }
#>     if (rlang::is_installed("collapse", version = "2.0.0")) {
#>         x <- collapse::rowbind(x, return = 2L)
#>     }
#>     else if (rlang::is_installed("data.table")) {
#>         x <- data.table::rbindlist(x)
#>         data.table::setDF(x)
#>     }
#>     else if (rlang::is_installed("vctrs")) {
#>         x <- vctrs::list_unchop(x, error_call = call)
#>     }
#>     else {
#>         x <- do.call(rbind.data.frame, x)
#>     }
#>     if (return_sf && !rlang::inherits_any(x, "sf")) {
#>         x <- sf::st_as_sf(x)
#>     }
#>     if (length(are_missing) > 0) {
#>         attr(x, "null_elements") <- are_missing
#>     }
#>     x
#> }
#> <bytecode: 0x000001911066e778>
#> <environment: namespace:arcgisutils>

library(arcgisgeocode)

n = 1001
addr <- rep("NULL", n)
addr[1] = "400 WASHINGTON AVE"
addr[500] = "105 W CHESAPEAKE AVE"
city <- sample(c("MIDDLE RIVER", "ESSEX", "DUNDALK", "TOWSON", "CATONSVILLE", "NULL"), n, replace = T)
city[c(1, 500)] = "TOWSON"

baltco_geo <- geocode_server(r"(https://bcgisdata.baltimorecountymd.gov/arcgis/rest/services/Geocoders/CompositeGeocoder/GeocodeServer)")

#mixing points and empty geometries creates differing classes for col 60, so cannot bind
tst_geo_all <- geocode_addresses(
  address = addr,
  city = city,
  geocoder = baltco_geo,
  .progress = FALSE
)
#> Error in collapse::rowbind(x, return = 2L): Class attribute on column 60 of item 2 does not match with column 60 of item 1.
```

<sup>Created on 2024-04-27 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by JosiahParry** [comment]
This should be resolved by https://github.com/R-ArcGIS/arcgisgeocode/commit/d8db4a3a1003e9e03542092185312f9f4f37d312

**Comment by JosiahParry** [comment]
> checks out. i am intrigued, though: when I try and add a second valid address into the middle of the vectors, it still returns GEOMETRYCOLLECTION EMPTY. see reprex:

I believe it is because the last location is sent in a batch all by itself lol

**Comment by JosiahParry** [comment]
If you're feeling frisky you can install rust via the exe here: https://rustup.rs/ then run `rustup target add x86_64-pc-windows-gnu` from your terminal and that should be all you need to install from source

**Comment by oonuttlet** [comment]
> > checks out. i am intrigued, though: when I try and add a second valid address into the middle of the vectors, it still returns GEOMETRYCOLLECTION EMPTY. see reprex:
> 
> I believe it is because the last location is sent in a batch all by itself lol

genius. replacing the _last_ item in the `addr` and `city` vectors with a valid address solves the issue, since i guess in that case neither batch is 100% unmatched. i'll try and get Rust up and running and see if i can install from source!

**Comment by oonuttlet** [comment]
fixed with [d8db4a3](https://github.com/R-ArcGIS/arcgisgeocode/commit/d8db4a3a1003e9e03542092185312f9f4f37d312)

thanks!

**Comment by oonuttlet** [comment]
forgot to hit close :)

**Comment by JosiahParry** [comment]
@oonuttlet bug fix has hit r-universe already :)
